version: "3.3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:2.4.14
    restart: always
    env_file:
      - ../../env/mongodb.env
    ports:
      - target: 27017
        published: 27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - target: 8081
        published: 8081
    env_file:
      - ../../env/mongo-express.env

  fastapi:
    container_name: fastapi
    build:
      context: ../../
      dockerfile: ./docker/common/Dockerfile
    depends_on:
      - mongodb
      - mongo-express
    ports:
      - target: 8000
        published: 8000

