language: generic
arch: arm64
os: linux
dist: focal
notifications:
  email: false
services:
  - docker
python:
  - '3.8'
node_js:
  - 12
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.27.4
cache:
  pip: true
  directories:
    - "$HOME/.cache/pip"
    - node_modules
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
before_install:
#  - echo "$DOCKER_PASSWORD" | sudo docker login --username "$DOCKER_USERNAME" --password-stdin
  - sudo docker build -t yannicnevhi/fastapi -f docker/common/Dockerfile .
  - sudo docker push yannicnevhi/fastapi
  - sudo docker container run -d --name mongodb -v mongo_data:/data/db -p 27017:27017 mongo
  - sudo docker container run -d --name fastapi -p 8000:8000 yannicnevhi/fastapi
  # install nodejs v12
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  - sudo apt-get install nodejs
  - sudo rm /usr/local/bin/docker-compose
  # check python version and install latest pip
  - python3 --version
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - sudo rm get-pip.py
  - pip3 --version
  - sudo docker ps
install:
  # newman for postman collection testing
  - sudo npm install -g newman
  # flake8 for code linting
  - pip3 install flake8
  # pushing later codecoverage to codecav
  - pip3 install codecov
jobs:
  include:
    - stage: flake8
      script: flake8 --config=flake8.ini
    - stage: postman-test
      script: newman run postman/dockerized/CocktailMachine.postman_collection.json
      after_success:
        - codecov
