language: minimal
arch: arm64
os: linux
dist: focal
notifications:
  email: false
services:
  - docker
python:
  - '3.8'
node_js:
  - 12
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.2
cache:
  pip: true
  directories:
    - "$HOME/.cache/pip"
    - node_modules
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
before_install:
  # install nodejs v12
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
  - sudo apt-get install nodejs
  - sudo rm /usr/local/bin/docker-compose
  # check python version and install latest pip
  - python3 --version
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py
  - pip3 --version
install:
  # newman for postman collection testing
  - sudo npm install -g newman
  # flake8 for code linting
  - pip3 install flake8
  # pushing later codecoverage to codecav
  - pip3 install codecov
before_script:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cd docker/production
script:
  - docker-compose build
  - docker-compose up -d
  - docker container ps
jobs:
  include:
    - stage: flake8
      script: flake8 --config=flake8.ini
    - stage: postman-test
      script: newman run postman/dockerized/CocktailMachine.postman_collection.json
      after_success:
        - codecov
