language: python
python:
    - "3.8"

arch: arm64
os: linux
dist: focal

before_install:
  - pip install codecov

install:
  # Install test dependencies.
  - pip install -r requirements.txt

jobs:
  include:
    - stage: flake8
      script: flake8 --config=flake8.ini --output-file=flake8Report.txt
    - stage: test
      script: pytest
      after_success:
        - codecov # submit coverage
