version: "3.3"

services:
  mongodb:
    container_name: alpine-mongodb-3.4.4
    build:
      context: ../../
      dockerfile: ./docker/common/mongodb/Dockerfile
    restart: always
    ports:
      - target: 27017
        published: 27017
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db

  fastapi:
    container_name: fastapi
    build:
      context: ../../
      dockerfile: ./docker/common/Dockerfile
    depends_on:
      - mongodb
    ports:
      - target: 8000
        published: 8000

volumes:
  mongo_data:


